#! /bin/sh
#
# /etc/rc.d/kwakd: start/stop kwakd
#

case "$1" in
  start)
    /usr/bin/kwakd -b -p 80
    ;;
  stop)
    killall -q kwakd
    ;;
  restart)
    $0 stop
    sleep 2
    $0 start
    ;;
  *)
    echo "usage: $0 [start|stop|restart]"
    ;;
esac

# End of file
